# Disable defaults
AllCops:
  Exclude:
    - "tmp/**/*"

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Layout/IndentHash:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/UnneededCopDisableDirective:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 110
  IgnoredPatterns:
    # Test descriptors
    - ^\s*(describe|it|context|scenario) ".+" do$

Metrics/MethodLength:
  Max: 12

Metrics/AbcSize:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Metrics/ParameterLists:
  CountKeywordArgs: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - _
    - a
    - b
    - i
    - n
    - k
    - v
    - x
    - y
    - id
    - op
    - to
    - tz

Style/AsciiComments:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - to
    - not_to
    - require
    - require_relative
    - raise
    - puts
    - validates # Sometimes this is called in a with_options block, confusing the cop.
    - class_eval
  Exclude:
    - Gemfile

Style/NestedTernaryOperator:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Bundler:
  Enabled: true
